name: wordpress-docker
services:
  database:
    container_name: database_tandira
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - "3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cloudflare_tunnel
    deploy:
      resources:
        limits:
          memory: 2048m

  phpmyadmin:
    container_name: phpmyadmin_tandira
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - cloudflare_tunnel

  wordpress:
    container_name: wordpress_tandira
    depends_on:
      - database
    image: wordpress:6.2.2-apache
    restart: unless-stopped
    ports:
      - "80"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - cloudflare_tunnel

volumes:
  db-data:

networks:
  cloudflare_tunnel:
    driver: bridge
