name: "${PROJECT_NAME}"
services:
  database:
    container_name: database_${PROJECT_NAME}
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    expose:
      - "3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tunnel_network
    deploy:
      resources:
        limits:
          memory: 2048m

  phpmyadmin:
    container_name: phpmyadmin_${PROJECT_NAME}
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - tunnel_network

  wordpress:
    container_name: wordpress_${PROJECT_NAME}
    depends_on:
      - database
    image: wordpress:php8.2-apache
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - tunnel_network

volumes:
  db-data:

networks:
  tunnel_network:
    driver: bridge
    external: true
