name: "${PROJECT_NAME}"
services:
  database:
    container_name: db_${PROJECT_NAME}
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    expose:
      - "3306"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tunnel_network
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Membatasi penggunaan CPU hingga 50% dari 1 core
          memory: '512M'    # Membatasi penggunaan memori hingga 512 MB
        reservations:
          cpus: '0.25'      # Memastikan setidaknya 25% dari 1 core dialokasikan
          memory: '256M'    # Memastikan setidaknya 256 MB memori dialokasikan

  phpmyadmin:
    container_name: pma_${PROJECT_NAME}
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - tunnel_network
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Membatasi penggunaan CPU hingga 50% dari 1 core
          memory: '512M'    # Membatasi penggunaan memori hingga 512 MB
        reservations:
          cpus: '0.25'      # Memastikan setidaknya 25% dari 1 core dialokasikan
          memory: '256M'    # Memastikan setidaknya 256 MB memori dialokasikan

  wordpress:
    container_name: wp_${PROJECT_NAME}
    depends_on:
      - database
    image: wordpress:php8.2-apache
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - tunnel_network
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Membatasi penggunaan CPU hingga 50% dari 1 core
          memory: '512M'    # Membatasi penggunaan memori hingga 512 MB
        reservations:
          cpus: '0.25'      # Memastikan setidaknya 25% dari 1 core dialokasikan
          memory: '256M'    # Memastikan setidaknya 256 MB memori dialokasikan

volumes:
  db-data:

networks:
  tunnel_network:
    driver: bridge
    external: true
